# fly.toml app configuration file generated for ai-backend-restless-cherry-5364 on 2025-06-18T11:13:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-backend-restless-cherry-5364'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  worker = "python worker.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
