'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';

const AI_BACKEND_URL = process.env.NEXT_PUBLIC_AI_BACKEND_URL || 'http://localhost:8000';

export default function SearchPage() {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<{ cypher_query: string; results: any[]; count: number } | null>(null);
  const [searchType, setSearchType] = useState<'basic' | 'crew'>('basic');
  
  const { status } = useSession();
  const router = useRouter();

  if (status === 'unauthenticated') {
    router.push('/auth/signin');
    return null;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query) {
      setError('Please enter a search query.');
      return;
    }

    setLoading(true);
    setError('');
    setResult(null);

    try {
      const endpoint = searchType === 'crew' ? '/api/ai/search/crew' : '/api/ai/search';
      const res = await fetch(`${AI_BACKEND_URL}${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.detail || 'An error occurred during search.');
      } else {
        if (searchType === 'crew') {
          // For crew search, the response format is different
          setResult({
            cypher_query: 'Generated by CrewAI agents',
            results: [{ analysis: data.analysis }],
            count: 1
          });
        } else {
          setResult(data);
        }
      }
    } catch (err) {
      setError('A network error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-4 sm:p-6 lg:p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Natural Language Search</h1>
        
        <form onSubmit={handleSubmit} className="space-y-4 mb-8">
          <div className="flex items-center space-x-2">
            <Input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Ask a question about your knowledge graph..."
              className="flex-grow"
            />
            <Button type="submit" disabled={loading}>
              {loading ? 'Searching...' : 'Search'}
            </Button>
          </div>
          
          <div className="flex items-center space-x-4">
            <label className="flex items-center space-x-2">
              <input
                type="radio"
                value="basic"
                checked={searchType === 'basic'}
                onChange={(e) => setSearchType(e.target.value as 'basic' | 'crew')}
              />
              <span>Basic Search</span>
            </label>
            <label className="flex items-center space-x-2">
              <input
                type="radio"
                value="crew"
                checked={searchType === 'crew'}
                onChange={(e) => setSearchType(e.target.value as 'basic' | 'crew')}
              />
              <span>AI Agent Search</span>
            </label>
          </div>

          <p className="text-sm text-gray-600">
            {searchType === 'basic' 
              ? 'Direct query generation and execution'
              : 'Enhanced analysis using CrewAI agents'
            }
          </p>
        </form>

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
            <p className="font-bold">Error</p>
            <p>{error}</p>
          </div>
        )}

        {result && (
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>
                  {searchType === 'crew' ? 'AI Agent Analysis' : 'Generated Cypher Query'}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <pre className="bg-gray-100 p-4 rounded-md overflow-x-auto">
                  <code>{result.cypher_query}</code>
                </pre>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Results ({result.count})</CardTitle>
              </CardHeader>
              <CardContent>
                {result.results.length > 0 ? (
                  <pre className="bg-gray-100 p-4 rounded-md overflow-x-auto max-h-96">
                    <code>{JSON.stringify(result.results, null, 2)}</code>
                  </pre>
                ) : (
                  <p>No results found.</p>
                )}
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
} 